// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXHXWKvG1f5KcXeeKJhLn9CUtzuYW5FNI',
    appId: '1:364333159941:web:b4e59fda40f79f1f292e6c',
    messagingSenderId: '364333159941',
    projectId: 'barber-shop-3d056',
    authDomain: 'barber-shop-3d056.firebaseapp.com',
    databaseURL: 'https://barber-shop-3d056-default-rtdb.firebaseio.com',
    storageBucket: 'barber-shop-3d056.firebasestorage.app',
    measurementId: 'G-2P6MYVQ33T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPv6sVLmMFQ_WRXMbEc1vOTL__dsUxiXI',
    appId: '1:364333159941:android:e3d7efd6e252f11b292e6c',
    messagingSenderId: '364333159941',
    projectId: 'barber-shop-3d056',
    databaseURL: 'https://barber-shop-3d056-default-rtdb.firebaseio.com',
    storageBucket: 'barber-shop-3d056.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5aWJhY9QkwBD0ZVyk8grJXQUorVrX1x0',
    appId: '1:364333159941:ios:2eaf40d09cb11bc3292e6c',
    messagingSenderId: '364333159941',
    projectId: 'barber-shop-3d056',
    databaseURL: 'https://barber-shop-3d056-default-rtdb.firebaseio.com',
    storageBucket: 'barber-shop-3d056.firebasestorage.app',
    iosBundleId: 'com.example.barbershop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5aWJhY9QkwBD0ZVyk8grJXQUorVrX1x0',
    appId: '1:364333159941:ios:2eaf40d09cb11bc3292e6c',
    messagingSenderId: '364333159941',
    projectId: 'barber-shop-3d056',
    databaseURL: 'https://barber-shop-3d056-default-rtdb.firebaseio.com',
    storageBucket: 'barber-shop-3d056.firebasestorage.app',
    iosBundleId: 'com.example.barbershop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXHXWKvG1f5KcXeeKJhLn9CUtzuYW5FNI',
    appId: '1:364333159941:web:44c42f0856a431cf292e6c',
    messagingSenderId: '364333159941',
    projectId: 'barber-shop-3d056',
    authDomain: 'barber-shop-3d056.firebaseapp.com',
    databaseURL: 'https://barber-shop-3d056-default-rtdb.firebaseio.com',
    storageBucket: 'barber-shop-3d056.firebasestorage.app',
    measurementId: 'G-QY53CV64XJ',
  );

}